# Generated by Django 5.2.10 on 2026-02-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_dark_mode_user_email_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('full_stack', 'Full Stack'), ('data_science', 'Data Science'), ('analyst', 'Analyst')], default='frontend', max_length=20),
        ),
    ]
