# Generated by Django 5.2.10 on 2026-02-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('full_stack', 'Full Stack'), ('data_analyst', 'Data Analyst')], default='frontend', max_length=20),
        ),
    ]
