# Generated by Django 5.2.10 on 2026-02-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_task_assigned_to_worklog_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.CharField(choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('full_stack', 'Full Stack Developer'), ('mobile_ios', 'Mobile iOS Developer'), ('mobile_android', 'Mobile Android Developer'), ('mobile_cross', 'Cross-platform Mobile Developer'), ('web_accessibility', 'Web Accessibility'), ('ui_ux', 'UI/UX Designer'), ('product_design', 'Product Designer'), ('qa_manual', 'Manual QA'), ('qa_automation', 'QA Automation'), ('test_engineer', 'Test Engineer'), ('devops', 'DevOps Engineer'), ('sre', 'Site Reliability Engineer'), ('cloud_engineer', 'Cloud Engineer'), ('platform_engineer', 'Platform Engineer'), ('systems_engineer', 'Systems Engineer'), ('network_engineer', 'Network Engineer'), ('security_engineer', 'Security Engineer'), ('appsec', 'Application Security'), ('netsec', 'Network Security'), ('data_analyst', 'Data Analyst'), ('data_engineer', 'Data Engineer'), ('data_scientist', 'Data Scientist'), ('ml_engineer', 'ML Engineer'), ('ai_engineer', 'AI Engineer'), ('mlops', 'MLOps Engineer'), ('database_admin', 'Database Administrator'), ('api_engineer', 'API Engineer'), ('software_architect', 'Software Architect'), ('embedded', 'Embedded Systems'), ('iot', 'IoT Engineer'), ('robotics', 'Robotics Engineer'), ('game_dev', 'Game Developer'), ('ar_vr', 'AR/VR Developer'), ('blockchain', 'Blockchain Developer'), ('devrel', 'Developer Advocate'), ('tech_writer', 'Technical Writer'), ('support_engineer', 'Support Engineer'), ('build_release', 'Build/Release Engineer'), ('infra_ops', 'Infrastructure Operations'), ('sys_admin', 'System Administrator'), ('it_support', 'IT Support'), ('business_analyst', 'Business Analyst'), ('product_manager', 'Product Manager'), ('gis', 'GIS Specialist')], default='frontend', max_length=20),
        ),
    ]
