# Generated by Django 5.2.10 on 2026-04-17 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_project_required_hours_worklog_task_task_progress'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='core_notifi_user_id_1cc5b6_idx',
            old_name='core_notifi_user_id_0c3651_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='core_notifi_user_id_cb8f07_idx',
            old_name='core_notifi_user_id_3d72ff_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='core_task_project_f427a2_idx',
            old_name='core_task_project_f7ecb6_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='core_task_project_ebbc98_idx',
            old_name='core_task_project_90b3ef_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='core_task_assigne_eec30b_idx',
            old_name='core_task_assigne_72d350_idx',
        ),
        migrations.RenameIndex(
            model_name='worklog',
            new_name='core_worklo_staff_i_970471_idx',
            old_name='core_worklo_staff_i_c226b2_idx',
        ),
        migrations.RenameIndex(
            model_name='worklog',
            new_name='core_worklo_status_78c09b_idx',
            old_name='core_worklo_status_5f2068_idx',
        ),
        migrations.RenameIndex(
            model_name='worklog',
            new_name='core_worklo_approve_d1e5d7_idx',
            old_name='core_worklo_approve_e0dbce_idx',
        ),
        migrations.RenameIndex(
            model_name='worklog',
            new_name='core_worklo_rejecte_ffda2c_idx',
            old_name='core_worklo_rejecte_b9e456_idx',
        ),
        migrations.RenameIndex(
            model_name='worklog',
            new_name='core_worklo_date_767bdc_idx',
            old_name='core_worklog_date_7a52f0_idx',
        ),
    ]
